# ============================================
# ACCSESSIBLE CONFIGURATION
# ============================================
# key_code 0 = Suara untuk SELURUH tombol keyboard
0=resources/tolong_BPxrsyS.wav

# (Opsional) Jika di masa depan ingin suara khusus per tombol, 
# hilangkan tanda '#' di bawah:
# 65=resources/key_a.wav      # A
# 66=resources/key_b.wav      # B  
# 67=resources/key_c.wav      # C
# 68=resources/key_d.wav      # D
# 13=resources/enter.wav      # Enter
# 32=resources/space.wav      # Space
# 8=resources/backspace.wav   # Backspace
# 9=resources/tab.wav         # Tab
# 27=resources/escape.wav     # Escape
# 164=resources/left_ctrl.wav # Left Ctrl
# 165=resources/right_ctrl.wav # Right Ctrl
# 162=resources/left_shift.wav # Left Shift
# 163=resources/right_shift.wav # Right Shift